### ISSUE TITLE
Typescript 5.6.x compiling issue

### ISSUE THREAD

**Issue by MikaKarjunen** [arogozine/LinqToTypeScript#32]
When trying to compile using typescript 5.6.x the following error message is shown.

error TS2320: Interface 'ArrayEnumerable<TSource>' cannot simultaneously extend types 'TSource[]' and 'IEnumerable<TSource>'.
  Named property '[Symbol.iterator]' of types 'TSource[]' and 'IEnumerable<TSource>' are not identical.

**Comment by MikaKarjunen** [comment]
This is a brilliant library and we'd love to keep using it. I hope we can come up with a solution of some sort.

**Comment by arogozine** [comment]
Seems like doing `Omit<IEnumerable<TSource>, typeof Symbol.iterator>  {` does the trick

Will try to push out 12.0.0-beta before end of week

**Comment by MikaKarjunen** [comment]
> Seems like doing `Omit<IEnumerable<TSource>, typeof Symbol.iterator> {` does the trick
> 
> Will try to push out 12.0.0-beta before end of week

That would be just brilliant!

**Comment by MikaKarjunen** [comment]
> See if this works, https://www.npmjs.com/package/linq-to-typescript/v/12.0.0-beta1


> See if this works, https://www.npmjs.com/package/linq-to-typescript/v/12.0.0-beta1
Seems to work just fine. No issues at all.

**Comment by MikaKarjunen** [comment]
I was wondering if there will be a final version coming out any time soon? We've had zero issues with the 12 beta.

**Comment by arogozine** [comment]
> I was wondering if there will be a final version coming out any time soon? We've had zero issues with the 12 beta.

I'll try to make some time for a late February release

**Comment by MikaKarjunen** [comment]
> I'll try to make some time for a late February release

That would be brilliant. You guys have done excellent job with the library.
